spring.application.name=leaddesk-backend

server.port=${PORT:8080}

spring.data.mongodb.uri=mongodb+srv://admin:LeadDesk123@cluster0.8m37wqj.mongodb.net/leaddesk?retryWrites=true&w=majority&authSource=admin

spring.data.mongodb.database=leaddesk

spring.data.mongodb.auto-index-creation=true